title: pidgy
author: deathbeds
copyright: '2021'
logo: pidgy.png
repository: {}
execute:
  execute_notebooks: cache
  exclude_patterns: []
only_build_toc_files: false
exclude_patterns: 
- _*
- .*
- jupyter_execute
- old
- .pytest_cache
- Untitled*
html:
  favico: ''
  use_edit_page_button: false
  use_repository_button: false
  use_issues_button: false
  extra_navbar: ''
  extra_footer: ''
  google_analytics_id: ''
  home_page_in_navbar: true
  baseurl: ''
  comments:
    hypothesis: false
    utterances: false
sphinx:
  extra_extensions: 
  - sphinx_sitemap
  - sphinx.ext.napoleon
  - sphinx.ext.todo
  - sphinx.ext.autodoc
  - sphinx.ext.viewcode
  - sphinx-jsonschema
  local_extensions: {}
  config: 
    html_baseurl: "https://pidgy.readthedocs.io/en/latest/"
    napoleon_numpy_docstring: True
    autodoc_inherit_docstrings: True
    autodoc_typehints: "none"
    nb_render_priority:
      html:
      - "application/vnd.jupyter.widget-view+json"
      - "application/javascript"
      - "text/html"
      - "image/svg+xml"
      - "image/png"
      - "image/jpeg"
      - "text/markdown"
      - "text/latex"
      - "text/plain"